### ISSUE TITLE
Different Nozzle Sizes (eg. 0.6) ? 

### ISSUE THREAD

**Issue by MoserElias** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#28] opened 2024-01-14 19:24 UTC
Hey, do you think there is any possibility to add a 0.6 Nozzle Profile, or does anyone have some experiences with the nozzle size and this prusa profile ?

**Comment by suchmememanyskill** [comment] 2024-01-14 20:23
Duplicate of #15

I don't have any plans to add this

**Closed** 2024-01-14 20:23 UTC
